//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 10:44:34 AM MSK 
//


package ru.krisnovitskaya.kris.market.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.krisnovitskaya.ws.market package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.krisnovitskaya.ws.market
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductByIdRequest }
     * 
     */
    public GetProductByIdRequest createGetProductByIdRequest() {
        return new GetProductByIdRequest();
    }

    /**
     * Create an instance of {@link GetProductByIdResponse }
     * 
     */
    public GetProductByIdResponse createGetProductByIdResponse() {
        return new GetProductByIdResponse();
    }

    /**
     * Create an instance of {@link ProductXML }
     * 
     */
    public ProductXML createProductXML() {
        return new ProductXML();
    }

    /**
     * Create an instance of {@link GetProductsRequest }
     * 
     */
    public GetProductsRequest createGetProductsRequest() {
        return new GetProductsRequest();
    }

    /**
     * Create an instance of {@link GetProductsResponse }
     * 
     */
    public GetProductsResponse createGetProductsResponse() {
        return new GetProductsResponse();
    }

    /**
     * Create an instance of {@link GetUserOrdersRequest }
     * 
     */
    public GetUserOrdersRequest createGetUserOrdersRequest() {
        return new GetUserOrdersRequest();
    }

    /**
     * Create an instance of {@link GetUserOrdersResponse }
     * 
     */
    public GetUserOrdersResponse createGetUserOrdersResponse() {
        return new GetUserOrdersResponse();
    }

    /**
     * Create an instance of {@link OrderXML }
     * 
     */
    public OrderXML createOrderXML() {
        return new OrderXML();
    }

    /**
     * Create an instance of {@link ItemOrder }
     * 
     */
    public ItemOrder createItemOrder() {
        return new ItemOrder();
    }

}
