//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.12 at 08:14:17 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.krisnovitskaya.com/ws/market", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.krisnovitskaya.kris.market.soap;
